#!/bin/bash

end="$(date --date="$1" +'%s')"
printf 'Counting down to %s (%s)\n' "$(date --date="$1")" "$end"
while (( $(date +'%s') < $((end-120)) ))
do
  printf '\r%s minutes     ' "$(((end-$(date +'%s'))/60))"
  sleep 1m
done

while (( $(date +'%s') < end ))
do
  printf '\r%s seconds     ' "$((end-$(date +'%s')))"
  sleep 1
done
printf '\n'
